#!/bin/bash
echo Setting up environment to work on the PARFLOW/PyWr project...
echo -------------------------------------------------------------
echo 1. Activating Python environment ...
source ~/python_envs/pywr_env/bin/activate 
echo 2. Starting Atom ...
atom ~/git_projects/parflow-pywr-moea
echo 3. Exporting PARFLOW_DIR variable ...
export PARFLOW_DIR=/home/lepton/parflow/install
